service: serverless-app

plugins:
  - serverless-dynamodb-local
  - serverless-offline #serverless-offline needs to be last in the list

custom:
  tableName: 'schema-table-${self:provider.stage}'
  dynamodb:
    start:
      migrate: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["SchemaDynamoDBTable", "Arn" ] }
  environment:
    SCHEMA_TABLE: ${self:custom.tableName}

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  getSchema:
    handler: index.handler
    events:
      - http: 'GET /schema/{proxy+}'
  getSchemas:
    handler: index.handler
    events:
      - http: 'GET /schemas'
  createSchema:
    handler: index.handler
    events:
      - http: 'POST /schema'

resources:
  Resources:
    SchemaDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: schemaId
            AttributeType: S
        KeySchema:
          -
            AttributeName: schemaId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}